language: go
go: 1.8

sudo: required

branches:
    only:
        - master

install:
    - go get -v github.com/spf13/hugo
    - hugo version
    - sudo pip install Pygments

script:
    - ./_scripts/publish.sh

